"""initial schema

Revision ID: 12b3aaebf72e
Revises: 
Create Date: 2026-03-23 16:08:28.390861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b3aaebf72e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_descriptions',
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('field_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('participant_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field_descriptions.field_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id'),
    sa.UniqueConstraint('participant_id', 'field_id', name='uq_participant_field')
    )
    op.create_table('studies',
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('study_name', sa.String(length=255), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id')
    )
    op.create_table('study_participants',
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('consent_all_fields', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id', 'participant_id')
    )
    op.create_table('study_required_fields',
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field_descriptions.field_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id', 'field_id')
    )
    op.create_table('study_participant_consented_fields',
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field_descriptions.field_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_id', 'participant_id'], ['study_participants.study_id', 'study_participants.participant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id', 'participant_id', 'field_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_participant_consented_fields')
    op.drop_table('study_required_fields')
    op.drop_table('study_participants')
    op.drop_table('studies')
    op.drop_table('participant_answers')
    op.drop_table('users')
    op.drop_table('field_descriptions')
    # ### end Alembic commands ###
