"""add study modifications

Revision ID: 253dc6d9d810
Revises: fac10747d45f
Create Date: 2026-04-28 20:42:40.230441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253dc6d9d810'
down_revision = 'fac10747d45f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_modifications',
    sa.Column('modification_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['study_issues.issue_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('modification_id')
    )
    op.create_table('study_modification_optional_fields',
    sa.Column('modification_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('modification_type', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field_descriptions.field_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modification_id'], ['study_modifications.modification_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('modification_id', 'field_id')
    )
    op.create_table('study_modification_required_fields',
    sa.Column('modification_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('modification_type', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field_descriptions.field_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modification_id'], ['study_modifications.modification_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('modification_id', 'field_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_approved')
        batch_op.drop_column('requested_role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_role', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.BOOLEAN(), nullable=True))

    op.drop_table('study_modification_required_fields')
    op.drop_table('study_modification_optional_fields')
    op.drop_table('study_modifications')
    # ### end Alembic commands ###
