"""add field type and field options

Revision ID: 5f9b86bd8778
Revises: e5f6a7b8c9d0
Create Date: 2026-04-30 12:42:10.919526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9b86bd8778'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_options',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field_descriptions.field_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('option_id'),
    sa.UniqueConstraint('field_id', 'value', name='uq_field_option_value')
    )
    with op.batch_alter_table('field_descriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_type', sa.String(length=50), nullable=False))

    with op.batch_alter_table('study_modifications', schema=None) as batch_op:
        batch_op.alter_column('issue_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_modifications', schema=None) as batch_op:
        batch_op.alter_column('issue_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('field_descriptions', schema=None) as batch_op:
        batch_op.drop_column('field_type')

    op.drop_table('field_options')
    # ### end Alembic commands ###
