"""add study issue tables

Revision ID: fac10747d45f
Revises: 6f76f99c4565
Create Date: 2026-04-11 16:56:05.134809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac10747d45f'
down_revision = '6f76f99c4565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_issues',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('regulator_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['regulator_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_table('study_issue_fields',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field_descriptions.field_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['study_issues.issue_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id', 'field_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    op.drop_table('study_issue_fields')
    op.drop_table('study_issues')
    # ### end Alembic commands ###
